import type { ConnectionState } from "@/state/types";

export type ConnectionEvent =
  | "CONNECT"
  | "OPEN"
  | "USER_MESSAGE"
  | "TOOL_CALL"
  | "TOOL_RESULT"
  | "STREAM_END"
  | "DROP"
  | "RESUME_SENT"
  | "RESUME_COMPLETE"
  | "FAIL"
  | "RESET";

const transitions: Record<ConnectionState, Partial<Record<ConnectionEvent, ConnectionState>>> = {
  DISCONNECTED: { CONNECT: "CONNECTING", RESET: "DISCONNECTED" },
  CONNECTING: { OPEN: "CONNECTED", DROP: "RECONNECTING", FAIL: "FAILED" },
  CONNECTED: { USER_MESSAGE: "STREAMING", TOOL_CALL: "WAITING_TOOL_RESULT", DROP: "RECONNECTING", FAIL: "FAILED" },
  STREAMING: { TOOL_CALL: "WAITING_TOOL_RESULT", STREAM_END: "CONNECTED", DROP: "RECONNECTING", FAIL: "FAILED" },
  WAITING_TOOL_RESULT: { TOOL_RESULT: "STREAMING", DROP: "RECONNECTING", STREAM_END: "CONNECTED", FAIL: "FAILED" },
  RECONNECTING: { CONNECT: "CONNECTING", OPEN: "RESUMING", FAIL: "FAILED" },
  RESUMING: { RESUME_SENT: "RESUMING", RESUME_COMPLETE: "CONNECTED", TOOL_CALL: "WAITING_TOOL_RESULT", USER_MESSAGE: "STREAMING", FAIL: "FAILED" },
  FAILED: { RESET: "DISCONNECTED", CONNECT: "CONNECTING" }
};

export function transitionConnection(current: ConnectionState, event: ConnectionEvent): ConnectionState {
  return transitions[current][event] ?? current;
}

export const stateMachineMermaid = `
stateDiagram-v2
  DISCONNECTED --> CONNECTING: CONNECT
  CONNECTING --> CONNECTED: OPEN
  CONNECTED --> STREAMING: USER_MESSAGE/TOKEN
  STREAMING --> WAITING_TOOL_RESULT: TOOL_CALL
  WAITING_TOOL_RESULT --> STREAMING: TOOL_RESULT
  STREAMING --> CONNECTED: STREAM_END
  CONNECTED --> RECONNECTING: DROP
  STREAMING --> RECONNECTING: DROP
  WAITING_TOOL_RESULT --> RECONNECTING: DROP
  RECONNECTING --> RESUMING: OPEN
  RESUMING --> CONNECTED: RESUME_COMPLETE
  CONNECTING --> FAILED: FAIL
  RESUMING --> FAILED: FAIL
`;
